### ISSUE TITLE
Make Informix project compilable

### ISSUE THREAD

**Issue by JohannesRabauer** [xdev-software/xapi-db-informix#1]
Project right now does not compile because of missing dependencies. There should be some way to fix this.

**Comment by AB-xdev** [comment]
Unable to make project compileable:
Informix JDBC driver 3 contains ``public static boolean t = false;`` inside ``IfxStatement``.
This variable is required for https://github.com/xdev-software/xapi-db-informix/blob/de516d3677d13fb8fc7df6717f87edd373b27621/src/main/java/xdev/db/informix/jdbc/InformixJDBCMetaData.java#L499

The variable is no longer present in JDBC driver version 4+ so we can't ensure compatibility.

Archiving the project.
